version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: journeyscape
volumes:
  mongodb:
